{% set name = "auto_rxn" %}
{% set version = "2023.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auto_rxn-{{ version }}.tar.gz
  sha256: ea9bd211d20fef5a1d9b0cd7c2c360d40f5d44636d652c5f01d1a848011b12fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - auto_rxn=auto_rxn.__main__:main

requirements:
  host:
    - python >=3.7
    - flit-core
    - pip
  run:
    - python >=3.7
    - appdirs
    - click
    - happi
    - pandas
    - bluesky
    - suitcase-csv
    - packaging

test:
  imports:
    - auto_rxn
  commands:
    #- pip check  # bluesky recipe has bad depndencies, breaks pip check, should check once upstream fixed
    - auto_rxn --help
  requires:
    - pip

about:
  home: https://github.com/uw-madison-chem-shops/auto_rxn
  summary: Python package for running chemical reactions as defined by recipe files.
  dev_url: https://github.com/uw-madison-chem-shops/auto_rxn
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
