{% set name = "auto_rxn" %}
{% set version = "2023.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auto_rxn-{{ version }}.tar.gz
  sha256: 55fb6384dbc50999f46206d887cc32e5bbc6c550f29fa3c371f95fd527825c38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - auto_rxn=auto_rxn.__main__:main
    - auto-rxn=auto_rxn.__main__:main

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - platformdirs
    - click
    - happi
    - pandas
    - bluesky
    - suitcase-csv
    - packaging
    - tomli
    - tomli-w

test:
  imports:
    - auto_rxn
  commands:
    #- pip check  # bluesky recipe has bad depndencies, breaks pip check, should check once upstream fixed
    - auto_rxn --help
    - auto-rxn --help
  requires:
    - pip

about:
  home: https://github.com/uw-madison-chem-shops/auto_rxn
  summary: Python package for running chemical reactions as defined by recipe files.
  dev_url: https://github.com/uw-madison-chem-shops/auto_rxn
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
